name: Makefile CI
permissions: 
  contents: read

on:
- push
- pull_request
- workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build toolchain container
      run: docker build . -t builder
    - uses: a
    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
